name: Renovate

on:
  workflow_dispatch:
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v43.0.14
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
